const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const os = require('os');
const bcrypt = require('bcryptjs');

const DEFAULT_STORE = path.join(os.homedir(), '.claude-session-hub', 'mobile-devices.json');
let STORE_PATH = DEFAULT_STORE;
const BCRYPT_ROUNDS = 10;
function _setStorePath(p) { STORE_PATH = p; }

// In-memory set of tokens that have been generated but not yet consumed
// by a successful registerDevice call. Key = plain token, value = expiresAt ms.
// Prevents arbitrary LAN peers from registering with self-generated tokens.
const PENDING_TOKENS = new Map();
const PENDING_TTL_MS = 5 * 60 * 1000; // 5 minutes

function _gcPendingTokens() {
  const now = Date.now();
  for (const [tok, expiresAt] of PENDING_TOKENS) {
    if (now >= expiresAt) PENDING_TOKENS.delete(tok);
  }
}

// For test isolation: clear all pending tokens between test runs.
function _clearPendingTokens() {
  PENDING_TOKENS.clear();
}

function _load() {
  try {
    return JSON.parse(fs.readFileSync(STORE_PATH, 'utf-8'));
  } catch (e) {
    if (e.code !== 'ENOENT') {
      console.error('[mobile-auth] devices file unreadable, starting empty:', e.message);
    }
    return { version: 1, devices: [] };
  }
}

function _save(data) {
  fs.mkdirSync(path.dirname(STORE_PATH), { recursive: true });
  const tmp = STORE_PATH + '.tmp';
  fs.writeFileSync(tmp, JSON.stringify(data, null, 2), { mode: 0o600 });
  fs.renameSync(tmp, STORE_PATH);
}

// Generate a random 256-bit token and register it in PENDING_TOKENS with a 5-min TTL.
// The caller (main.js pairing flow) passes it to the mobile client via QR code.
// registerDevice will only accept tokens that are currently pending.
function generateToken() {
  _gcPendingTokens();
  const token = crypto.randomBytes(32).toString('hex');
  PENDING_TOKENS.set(token, Date.now() + PENDING_TTL_MS);
  return token;
}

async function registerDevice(token, deviceId, name, ip) {
  if (!token || !deviceId) return { ok: false, reason: 'bad-args' };
  _gcPendingTokens();
  // Require the token to have been generated by this server process
  if (!PENDING_TOKENS.has(token)) return { ok: false, reason: 'token-not-pending' };

  const data = _load();
  if (data.devices.some(d => d.deviceId === deviceId)) {
    return { ok: false, reason: 'deviceid-already-registered' };
  }
  // ONE bcrypt call — the O(N) scan for token-already-bound is gone; the
  // pending-token predicate provides a stronger and cheaper guarantee.
  const hash = await bcrypt.hash(token, BCRYPT_ROUNDS);
  data.devices.push({
    deviceId,
    name: name || 'Unknown',
    tokenHash: hash,
    createdAt: Date.now(),
    lastSeenAt: Date.now(),
    lastIp: ip || null,
  });
  _save(data);
  // Consume the token so it cannot be reused
  PENDING_TOKENS.delete(token);
  return { ok: true };
}

async function verifyToken(token, deviceId) {
  if (!token || !deviceId) return { ok: false };
  const data = _load();
  for (const d of data.devices) {
    if (d.deviceId !== deviceId) continue;
    if (await bcrypt.compare(token, d.tokenHash)) {
      return { ok: true, device: d };
    }
  }
  return { ok: false };
}

function touchDevice(deviceId, ip) {
  const data = _load();
  const d = data.devices.find(x => x.deviceId === deviceId);
  if (!d) return { ok: false, reason: 'not-found' };
  d.lastSeenAt = Date.now();
  if (ip) d.lastIp = ip;
  _save(data);
  return { ok: true };
}

function listDevices() {
  return _load().devices.map(({ tokenHash, ...pub }) => pub);
}

function revokeDevice(deviceId) {
  const data = _load();
  const before = data.devices.length;
  data.devices = data.devices.filter(d => d.deviceId !== deviceId);
  if (data.devices.length === before) return { ok: false, reason: 'not-found' };
  _save(data);
  return { ok: true };
}

module.exports = {
  generateToken,
  registerDevice,
  verifyToken,
  touchDevice,
  listDevices,
  revokeDevice,
  _setStorePath,
  _clearPendingTokens,
};
